### ISSUE TITLE
"not key value encoding-compliant" problem

### ISSUE THREAD

**Issue by ghost** [evermeer/AlamofireXmlToObjects#1]
I have hit this problem with a new API XML feed.

> 2016-04-12 13:35:29.178 Vault[55707:19474924]  
> WARNING: The class 'XXX' is not key value coding-compliant for the key '__name'
> There is no support for optional type, array of optionals or enum properties.
> As a workaround you can implement the function 'setValue forUndefinedKey' for this. See the unit tests for more information

previously, working with a different API (Json) and your AlamofireJsonToObjects library I solved the same problem by defining all the Json keys and also following your advice to add 

```
override internal func propertyMapping() -> [(String?, String?)] {
        return [("ignoredProperty",nil), ("propertyInObject","keyInJson")]
}
```

I am now stuck on this XML feed API and using AlamofireXmlToObjects, since it seems to generate some internal values I don't recognise from the API docs (_name, _version, _copyright) and there are also quite a few keys I would prefer to ignore

Adding the propertyMapping() override as above doesn't help -- I noticed the final parameter is "keyInJson". 

Would appreciate any advice you might have with this

**Comment by evermeer** [comment]
Apparently Xml2Dictionary has generated those values from your XML. You can find those in the dictionary. If you would like to ignore those fields, then your propertyMapping will look like this:

```
override internal func propertyMapping() -> [(String?, String?)] {
        return [(nil,"_name"), (nil,"_version"), (nil,"_copyright")]
}
```

**Comment by ghost** [comment]
Thanks for the very speedy reply

Unfortunately adding the propertyMapping override had no effect. The first few lines of the xml are a below

``` xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<JDBOR date="2016-04-01 04:12:10" version="1.1.4 / 4.1.3 ORPHANET [2014-10-03]" copyright="Orphanet (c) 2016">
  <DisorderList count="9366">
    <Disorder id="17601">
      <OrphaNumber>166024</OrphaNumber>
      <ExpertLink lang="en">http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&amp;Expert=166024</ExpertLink>
      <Name lang="en">Multiple epiphyseal dysplasia, Al-Gazali type</Name>
      <DisorderFlagList count="1">
        <DisorderFlag id="476">
          <Label>on-line</Label>

The warning is also shown for _date and DisorderList and adding them to the return list makes no difference
```

**Comment by evermeer** [comment]
I have put it all in a working unit test.
You can find it at: https://github.com/evermeer/AlamofireXmlToObjects/blob/master/AlamofireXmlToObjectsTests/AlamofireXmlToObjects2Tests.swift

**Comment by ghost** [comment]
Thank you very much for the help. 

This test worked well (with the addition of an "import AlamofireXmlToObjects") and is a very clear example that helps me understand how to use the library.

Very grateful for the quick turnaround on a solution and for making this and other libraries available
