### ISSUE TITLE
Cannot invoke 'responseObject ' with argument list of type '((WeatherResponse?,NSError?) -> ())'

### ISSUE THREAD

**Issue by aosterthun** [evermeer/AlamofireXmlToObjects#2]
Hey,

I would really like to use your CocoaPod but I can't get it to work. Even the sample code won't work.
Any suggestions why this error is popping up ?

**Comment by evermeer** [comment]
If you download AlamofireXmlToObject (press download zip at https://github.com/evermeer/AlamofireXmlToObjects)  and then execute a pod update from the terminal you should see that the folowing 2 library versions are loaded:
- Alamofire (3.4.0)
- EVReflection (2.31.0)
  After that you should be able to run the tests

**Comment by aosterthun** [comment]
First I'm really thankful you replied that fast (or at all) ! 

After updating the Podfile (don't wonder it's a .txt couldn't upload it otherwise) I got the example project to work. 
[Podfile.txt](https://github.com/evermeer/AlamofireXmlToObjects/files/265156/Podfile.txt)
I'm still wondering why it throughs that error in my project, because I installed the same dependencies.
[Podfile[custom].txt](https://github.com/evermeer/AlamofireXmlToObjects/files/265158/Podfile.custom.txt)

If it helps I could add you to the repo I'm trying to install it on.

**Comment by aosterthun** [comment]
Ok I fixed it.
You should maybe edit your README.md from:
(response: WeatherResponse?, error: NSError?)
to:
(response: Result< WeatherResponse,NSError>)

**Comment by aosterthun** [comment]
Other question how do I represent properties of tags in a class ? Which datatypes do I use ? For example I have the following xml tag:
`<device name="HM-CC-RT-DN KEQ0652567" ise_id="1237" unreach="false" sticky_unreach="false" config_pending="false">`

**Comment by evermeer** [comment]
Ah! yes, the signature was changed quite some time ago... I will update the sample in a moment.

In your sample you will get a sub object for device. That device sub object will have a _name, _ise_id, _unreach, _sticky_unreach and _config_pending property. attributes will get an underscore in front of the name.

You can see how this works in the test that you can find here:
https://github.com/evermeer/AlamofireXmlToObjects/blob/58f2aea01e76f35d7cda969d1310bafa77480541/AlamofireXmlToObjectsTests/AlamofireXmlToObjects2Tests.swift#L15-L15

You could also just define 1 object without properties and run it. In the console log you will find warnings that specific properties could not be found. Then just add those properties to your object.

**Comment by aosterthun** [comment]
Ok last comment (I swear :D ) I also got that to work.
Last I have some general comments to the lib. 
In my case I had to define a __name var for a tag that didn't had any properties it now stores the name of the tag don't know why that there don't have it in any other case. 
It would be nice if the whitespace would be removed automatically so you don't have to write the underscore in front of every property.

But all in all I'm really happy that I didn't had to write such a lib by myself. So at the and a big thanks! Will recommend it!

**Comment by evermeer** [comment]
The __name and the _ for attributes comes from the XML2Dictionary library. That is a library that is not written by me.

AlamofireXMLToObjects itself has a very limited implementation. It's only a bridge between XML2Dictionary, AlamoFire and EVReflection. See here the entire code of the library. See how small it is? [AlamofireXmlToObject library](https://github.com/evermeer/AlamofireXmlToObjects/blob/58f2aea01e76f35d7cda969d1310bafa77480541/AlamofireXmlToObjects/AlamofireXmlToObjects.swift#L14-L14) It's only 70 lines of which half is comment.

**Comment by aosterthun** [comment]
Ok I didn't knew that I relatively new to swift programming and therefore don't know many of the common libs. Normally I'm working in C++, C, PHP, Python and some other Web languages.

**Comment by evermeer** [comment]
Tip: EVReflection supports property mapping. You can use that to ignore properties or to change a property name. For instance you could Implement something like this:

```
    override public func propertyMapping() -> [(String?, String?)] {
        return [("__name", nil), ("_name", "Name"), ("ise_id", "IseId")]
    }
```

You could also put that in a base class so that it's used in all your objects.
in the case above the __name will be ignored and _name will be changed to Name
