### ISSUE TITLE
Unable to Parse

### ISSUE THREAD

**Issue by manish-1612** [evermeer/AlamofireXmlToObjects#4]
I am trying to parse a XML which looks like this : 

`<requestl>
<qlist>
<piname>MONTY CHICOLA</piname>
<picell>318-730-5705</picell>
<pihome>318-442-3893</pihome>
<rinum>FAAAAAM7</rinum>
<dev>$00046728</dev>
<riapt>KFOE</riapt>
<rifbo>00001</rifbo>
<ridatr>08/02/2016-03:05</ridatr>
<ridats/>
<riacft>N5WF</riacft>
<riftyp>JET/A</riftyp>
<rifunt>GAL</rifunt>
<rifuel>46549</rifuel>
<xifptx/>
<rifpt>05990</rifpt>
<xifpsx/>
<rifps>09990</rifps>
<riinf1>SHELL 15 W 50</riinf1>
<riinf2/>
<ritarr>03:03</ritarr>
<ridata>08/02/2016</ridata>
<ridumd>08/02/2016 03:03</ridumd>
<risort>20160802 20160802</risort>
<ridumy>08/02/2016 03:03</ridumy>
<ritdep>03:03</ritdep>
<riddat>08/02/2016</riddat>
<rinotr>N</rinotr>
<rinotc>N</rinotc>
<rinots>*</rinots>
<ripdrp>0</ripdrp>
<rippck>0</rippck>
<riex2/>
<xifpmx/>
<rifpm>09960</rifpm>
<xifpax/>
<rifpa>90999</rifpa>
<xifpix/>
<rifpi>99990</rifpi>
<xifpox/>
<rifpo>00999</rifpo>
<rihang/>
<ristat>New Request</ristat>
<rirepy/>
<riext1>Crew Car</riext1>
<riex1>N</riex1>
<paname>CESSNA</paname>
<pamodl>550</pamodl>
<pafuel>AVGAS</pafuel>
<riinst/>
<riloc>H-1</riloc>
<rifpum>00000</rifpum>
<ritpum/>
<riqoil>940</riqoil>
<ritoil>SHELL 15 W 50</ritoil>
<riusro/>
<riapu/>
<fbnam>Forbes Million Air</fbnam>
<fbadd1>Forbes Field Bldg 610</fbadd1>
<fbphon>877-862-0950</fbphon>
<fbnam>Forbes Million Air</fbnam>
</qlist>
</requestl>`

I am not able to parse and extract data.
Can you please help me out. 
Thank You

**Comment by evermeer** [comment]
Here you can see a working unit test for this XML
https://github.com/evermeer/AlamofireXmlToObjects/blob/bda402badcb1a800d8002c2a15f6cea6a97f405c/AlamofireXmlToObjectsTests/Issue4Test.swift#L42-L42

Just expand the QList object with all the properties.

**Comment by manish-1612** [comment]
Thank You Evermeer.

**Comment by manish-1612** [comment]
Hi Evermeer,

The XML Response that I sent you wrong, there was a mistake while copy paste. Sorry for wasting your time and energy. Here is the correct XML.

`<requestl>
<qlist>
<piname>MONTY CHICOLA</piname>
<picell>318-730-5705</picell>
<pihome>318-442-3893</pihome>
<rinum>FAAAAANI</rinum>
<dev>$00046728</dev>
<riapt>KFOE</riapt>
<rifbo>00001</rifbo>
<ridatr>08/04/2016 07:06</ridatr>
<ridats/>
<riacft>N2244</riacft>
<riftyp>AVGAS</riftyp>
<rifunt>GAL</rifunt>
<rifuel>0</rifuel>
</qlist>
<qlist>
<piname>MONTY CHICOLA</piname>
<picell>318-730-5705</picell>
<pihome>318-442-3893</pihome>
<rinum>FAAAAANL</rinum>
<dev>$00046728</dev>
<riapt>KFOE</riapt>
<rifbo>00001</rifbo>
<ridatr>08/04/2016-18:58</ridatr>
<ridats/>
<riacft>N55MC</riacft>
<riftyp>AVGAS</riftyp>
<rifunt>GAL</rifunt>
<rifuel>00100</rifuel>
</qlist>
<qlist>
<piname>MONTY CHICOLA</piname>
<picell>318-730-5705</picell>
<pihome>318-442-3893</pihome>
<rinum>FAAAAANM</rinum>
<dev>$00046728</dev>
<riapt>KAEX</riapt>
<rifbo>00001</rifbo>
<ridatr>08/04/2016-19:01</ridatr>
<ridats/>
<riacft>N5JT</riacft>
<riftyp>JET/A</riftyp>
<rifunt>GAL</rifunt>
<rifuel>100</rifuel>
</qlist>
<qlist>
<piname>MONTY CHICOLA</piname>
<picell>318-730-5705</picell>
<pihome>318-442-3893</pihome>
<rinum>FAAAAANN</rinum>
<dev>$00046728</dev>
<riapt>KAEX</riapt>
<rifbo>00001</rifbo>
<ridatr>08/04/2016-19:06</ridatr>
<ridats/>
<riacft>N2244</riacft>
<riftyp>AVGAS</riftyp>
<rifunt>GAL</rifunt>
<rifuel>0</rifuel>
</qlist>
</requestl>`

Please help me out. Thanks in advance.
