### ISSUE TITLE
  Issue - #4, Unable to Parse

### ISSUE THREAD

**Issue by manish-1612** [evermeer/AlamofireXmlToObjects#5]
Hi Evermeer,

The XML Response that I sent you wrong, there was a mistake while copy paste. Sorry for wasting your time and energy. Here is the correct XML.

`<requestl> <qlist> <piname>MONTY CHICOLA</piname> <picell>318-730-5705</picell> <pihome>318-442-3893</pihome> <rinum>FAAAAANI</rinum> <dev>$00046728</dev> <riapt>KFOE</riapt> <rifbo>00001</rifbo> <ridatr>08/04/2016 07:06</ridatr> <ridats/> <riacft>N2244</riacft> <riftyp>AVGAS</riftyp> <rifunt>GAL</rifunt> <rifuel>0</rifuel> </qlist> <qlist> <piname>MONTY CHICOLA</piname> <picell>318-730-5705</picell> <pihome>318-442-3893</pihome> <rinum>FAAAAANL</rinum> <dev>$00046728</dev> <riapt>KFOE</riapt> <rifbo>00001</rifbo> <ridatr>08/04/2016-18:58</ridatr> <ridats/> <riacft>N55MC</riacft> <riftyp>AVGAS</riftyp> <rifunt>GAL</rifunt> <rifuel>00100</rifuel> </qlist> <qlist> <piname>MONTY CHICOLA</piname> <picell>318-730-5705</picell> <pihome>318-442-3893</pihome> <rinum>FAAAAANM</rinum> <dev>$00046728</dev> <riapt>KAEX</riapt> <rifbo>00001</rifbo> <ridatr>08/04/2016-19:01</ridatr> <ridats/> <riacft>N5JT</riacft> <riftyp>JET/A</riftyp> <rifunt>GAL</rifunt> <rifuel>100</rifuel> </qlist> <qlist> <piname>MONTY CHICOLA</piname> <picell>318-730-5705</picell> <pihome>318-442-3893</pihome> <rinum>FAAAAANN</rinum> <dev>$00046728</dev> <riapt>KAEX</riapt> <rifbo>00001</rifbo> <ridatr>08/04/2016-19:06</ridatr> <ridats/> <riacft>N2244</riacft> <riftyp>AVGAS</riftyp> <rifunt>GAL</rifunt> <rifuel>0</rifuel> </qlist> </requestl>`

Also I have a class containing all the properties under qlist. What I want is that the properties under qlist to be parsed as an object of the class. 
Please help me out with this.
Thanks in advance.

**Comment by evermeer** [comment]
I updated the unit test. The only change you need is to change the qlist property from an object to an object array. 

When you run the unit test, you will see  a lot of warnings in the output log. Those are for the properties that I did not add to the object. You have to complete the object.
