### ISSUE TITLE
swift 3 issue

### ISSUE THREAD

**Issue by hanssl** [evermeer/AlamofireXmlToObjects#7]
It does not look like this project has been converted to Swift 3.  I tried letting Xcode 8 do the conversion but resulted in about 30 compiler errors.

**Comment by evermeer** [comment]
If you have only 30 errors, then I assume you were using the Swift 3 brach of EVReflection? Now that Xcode 8 GM is out, I will start moving all my libraries to Swift 3 into the main branch. This will probably be done within a week.

**Comment by evermeer** [comment]
There is now a Swift 3 branch. In a week or 2 I will merge it to master.
