### ISSUE TITLE
Generic type 'Result' specialized with too many type parameters (got 2, but expected 1)

### ISSUE THREAD

**Issue by tecexpert** [evermeer/AlamofireXmlToObjects#9]
Error in line:
`api.responseObject { (response: Result< WeatherResponse, NSError>) in`

**Comment by evermeer** [comment]
Alamofire has changed it's result signature. It has changed to:

```
Alamofire.request(URL)
            .responseObject { (response: DataResponse<WeatherResponse>) in
```

I see I have the old format still in the readme. I will update that now.

**Comment by evermeer** [comment]
I updated the readme
